import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './Login'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kyle Parry React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Login />
    </div>
  )
}
